language: swift
osx_image: xcode63
compiler:
  - clang

branches:
  only:
    - master

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xctools --no-rdoc --no-ri --no-document --quiet

script:
  - xctool -project Project/Player.xcodeproj -scheme Debug -sdk iphonesimulator8.0 build analyze
