language: objective-c
osx_image: xcode63
compiler:
  - clang

branches:
  only:
    - master

before_install:
  - gem install xcpretty -N
  - brew update
  - brew reinstall xctool

script: xctool -project Project/Player.xcodeproj -scheme Debug -sdk iphonesimulator8.3 build analyze | xcpretty -c
