language: swift
osx_image: xcode63
compiler:
  - clang

branches:
  only:
    - master

before_install:
  - brew install xctool

script:
  - xctool -project Project/Player.xcodeproj -scheme Debug -sdk iphonesimulator8.0 build analyze
